name: Build Deploy and Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Build
        run: |
          npm ci
          npm run build
        env:
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}  # TODO: Remove when no longer needed

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_GRASS_0E1BAB20F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "dist" # App source code path
          api_location: "api" # Api source code path - optional
          # app_artifact_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  # e_to_e_test_in_staging_job:
  #   if: github.event_name == 'pull_request' && github.event.action != 'closed'
      # To get this working, I'll need the location of the staged site, which is always
      # https://<SUBDOMAIN>-<PULL_REQUEST_ID>.<AZURE_REGION>.azurestaticapps.net 
      # or the location of the production site which is currently https://mango-grass-0e1bab20f.azurestaticapps.net
      # where:
      #   <SUBDOMAIN> for MatrX is currently mango-grass-0e1bab20f
      #   <PULL_REQUEST_ID> get from the environment variable GITHUB_REF as described here: https://github.com/actions/checkout/issues/58
      #   <AZURE_REGION> is eastus2
      # Build the host base URL inside of the cypress tests themselves. Fall back to localhost:7071 if no GITHUB_REF
      # 
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     build: npm run build --if-present
      #     start: npm start
      #     wait-on: http://localhost:8080
      #     browser: chrome  # or firefox or edge with runs-on: windows-latest
      #     env:
      #       CYPRESS_GITHUB_REF: ${{github.ref}}  # I think this will do the trick

  # smoke_test_in_prod_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_GRASS_0E1BAB20F }}
          action: "close"
